version: '3.8'

services:
  # app:
  #   container_name: dotnet_app
  #   build: .
  #   ports:
  #     - "8080:5000"
  #     - "8081:5001"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - DOTNET_USE_POLLING_FILE_WATCHER=1
  #     - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydb;Username=myuser;Password=mypassword
  #     - Redis__ConnectionString=redis:6379
  #   depends_on:
  #     - db
  #     - redis

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
